name: My Open Catalogi Workflow

permissions:
  contents: write
  
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Update publiccode.yaml
        uses: OpenCatalogi/opencatalogi-action@0.1.0-main.7.b1bab8f
